export  const sportList: string[] = [
    "Hockey",
    "Soccer",
    "Football",
    "Flag Football",
    "Basketball",
    "Ultimate Frisbee",
    "Baseball",
    "Tennis",
    "Running",
    "SpikeBall",
    "Lacrosse",
    "Field Hockey",
    "Volleyball",
    "Lifting",
    "Handball",
    "Rock Climbing",
    "Biking",
    "Roller Blading",
    "Swimming",
    "Figure Skating",
    "Golf",
    "Sailing",
    "Surfing",
    "Kayaking",
    "Racquetball",
    "Table Tennis",
    "Hiking",
    "Paint Ball"
];