import { Group } from "./group";

export function getMockList(): Group[] {
    return ([
        {
            userID: '1a2b3c4d',
            gameID: '234n',
            active: true,
            sport: 'hockey',
            region: {
                lat: 25,
                lon: 24,
                latDelta: 1,
                lonDelta: 1,
            },
            skillLevel: 'Intermediate',
            openSpots: 5,
            playingCurrently: [],
            message: '',    
        }
    ])
}

export const GroupList: Group[] = [
    {
        userID: '1a2b3c4d',
        gameID: '234n',
        active: true,
        sport: 'hockey',
        region: {
            lat: 25,
            lon: 24,
            latDelta: 1,
            lonDelta: 1,
        },
        skillLevel: 'intermediate',
        openSpots: 5,
        playingCurrently: [],
        message: '',    
    },
    {
        userID: '234mfie4',
        gameID: '83475jkfd',
        active: true,
        sport: 'soccer',
        region: {
            lat: 25,
            lon: 24,
            latDelta: 1,
            lonDelta: 1,
        },
        skillLevel: 'easy',
        openSpots: 5,
        playingCurrently: [],
        message: '',    
    },
    // {
    //     userID: '9345semf',
    //     gameID: '237747id',
    //     active: true,
    //     sport: 'frisbee',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'skilled',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '1a2b3c4d',
    //     gameID: '234n',
    //     active: true,
    //     sport: 'hockey',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'intermediate',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '234mfie4',
    //     gameID: '83475jkfd',
    //     active: true,
    //     sport: 'soccer',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'easy',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '9345semf',
    //     gameID: '237747id',
    //     active: true,
    //     sport: 'frisbee',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'skilled',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '1a2b3c4d',
    //     gameID: '234n',
    //     active: true,
    //     sport: 'hockey',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'intermediate',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '234mfie4',
    //     gameID: '83475jkfd',
    //     active: true,
    //     sport: 'soccer',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'easy',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '9345semf',
    //     gameID: '237747id',
    //     active: true,
    //     sport: 'frisbee',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'skilled',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '1a2b3c4d',
    //     gameID: '234n',
    //     active: true,
    //     sport: 'hockey',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'intermediate',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '234mfie4',
    //     gameID: '83475jkfd',
    //     active: true,
    //     sport: 'soccer',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'easy',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '9345semf',
    //     gameID: '237747id',
    //     active: true,
    //     sport: 'frisbee',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'skilled',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '1a2b3c4d',
    //     gameID: '234n',
    //     active: true,
    //     sport: 'hockey',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'intermediate',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '234mfie4',
    //     gameID: '83475jkfd',
    //     active: true,
    //     sport: 'soccer',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'easy',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // },
    // {
    //     userID: '9345semf',
    //     gameID: '237747id',
    //     active: true,
    //     sport: 'frisbee',
    //     region: {
    //         lat: 25,
    //         lon: 24,
    //         latDelta: 1,
    //         lonDelta: 1,
    //     },
    //     skillLevel: 'skilled',
    //     openSpots: 5,
    //     playingCurrently: [],
    //     message: '',    
    // }
]